# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Input model for node_self_healing_dispatch_orchestrator [OMN-12208].

ModelSelfHealingDispatchRequest: carries the ticket list or epic ID and
execution parameters consumed by the orchestrator when triggered via
onex.cmd.omnimarket.self-healing-dispatch-start.v1.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ModelSelfHealingDispatchRequest(BaseModel):
    """Input to the self-healing dispatch orchestrator.

    Exactly one of ticket_ids or epic_id must be non-empty. The orchestrator
    fails fast if neither or both are provided.

    All parameters mirror the /onex:self_healing_dispatch skill surface defined
    in omniclaude/plugins/onex/skills/self_healing_dispatch/SKILL.md.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    ticket_ids: tuple[str, ...] = Field(
        default=(),
        description=(
            "Ordered tuple of Linear ticket IDs (OMN-XXXX format). "
            "Mutually exclusive with epic_id."
        ),
    )
    epic_id: str = Field(
        default="",
        description=(
            "Linear epic ID. When set, the orchestrator decomposes the epic "
            "into child tickets before dispatching. Mutually exclusive with ticket_ids."
        ),
    )
    repo_hints: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Optional mapping of ticket ID → repo name "
            "(e.g. {'OMN-1234': 'omniclaude'}). "
            "Tickets absent from this map are resolved from Linear metadata."
        ),
    )
    run_id: str = Field(
        default="",
        description=(
            "Correlation ID for this orchestration run. "
            "Auto-generated by the orchestrator if empty."
        ),
    )
    max_redispatches: int = Field(
        default=2,
        ge=0,
        description=(
            "Maximum number of redispatch attempts per stalled ticket before "
            "escalating to Blocked. Must be >= 0."
        ),
    )
    healthcheck_interval_seconds: int = Field(
        default=120,
        ge=10,
        description=(
            "Polling interval in seconds for the agent_healthcheck monitoring loop. "
            "Must be >= 10."
        ),
    )
    dry_run: bool = Field(
        default=False,
        description=(
            "When true, resolve ticket groups and emit orchestration_planned event "
            "without launching any workers."
        ),
    )
