# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Golden-equivalence proof for the ticket-classify def-B flip (OMN-14799).

Second bounded Outcome-A RSD canary via delegation. ``HandlerTicketClassify.handle()``
moved from ``handle(correlation_id, tickets) -> ModelTicketClassifyOutput`` (def-A,
two positional params -> non-canonical, RuntimeLocal-undispatchable per OMN-13711) to
the canonical ``handle(request) -> ModelTicketClassifyOutput`` (def-B, single
typed-payload positional; ``correlation_id`` / ``tickets`` read from
``request.correlation_id`` / ``request.tickets``). The handler body was regenerated by
a local model (``onex delegate`` -> Qwen3.6-35B-A3B, single attempt, quality gate
passed, $0); the classification logic is unchanged.

The goldens under ``tests/fixtures/golden/node_ticket_classify_compute/*.json`` were
recorded by replaying each scenario through the pre-flip def-A ``handle(cid, tickets)``
body and capturing byte-canonical output + a sha256 fingerprint. This durable
regression drives the SAME recorded inputs through the live def-B ``handle(request)``
and asserts byte/fingerprint-identical output — so a future edit to this handler
cannot silently change behavior without failing here (OMN-14589 style, not the
non-canonical adequacy_receipt.py path).

``test_fingerprint_discriminates`` proves the oracle is not a vacuous green: a
one-field perturbation of a recorded output changes the fingerprint.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest
import yaml

from omnimarket.nodes.node_ticket_classify_compute.handlers.handler_ticket_classify import (
    HandlerTicketClassify,
)
from omnimarket.nodes.node_ticket_classify_compute.models.model_ticket_classify_input import (
    ModelTicketClassifyInput,
)
from omnimarket.nodes.node_ticket_classify_compute.models.model_ticket_classify_output import (
    ModelTicketClassifyOutput,
)
from omnimarket.nodes.node_ticket_classify_compute.models.model_ticket_for_classification import (
    ModelTicketForClassification,
)

pytestmark = pytest.mark.unit

_REPO_ROOT = Path(__file__).resolve().parents[4]
_GOLDEN_DIR = (
    _REPO_ROOT / "tests" / "fixtures" / "golden" / "node_ticket_classify_compute"
)
_CONTRACT_PATH = (
    _REPO_ROOT
    / "src"
    / "omnimarket"
    / "nodes"
    / "node_ticket_classify_compute"
    / "contract.yaml"
)

# Recorded from the pre-flip def-A handler; the reviewed scenario pool size.
_EXPECTED_GOLDEN_COUNT = 12


def _fingerprint(output_json: dict[str, Any]) -> str:
    canonical = json.dumps(output_json, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()


def _golden_files() -> list[Path]:
    files = sorted(_GOLDEN_DIR.glob("*.json"))
    assert files, f"no golden fixtures found under {_GOLDEN_DIR}"
    return files


@pytest.mark.asyncio
@pytest.mark.parametrize("golden_path", _golden_files(), ids=lambda p: p.stem)
async def test_handle_reproduces_recorded_golden(golden_path: Path) -> None:
    """def-B ``handle(request)`` on the recorded input == the recorded output."""
    golden: dict[str, Any] = json.loads(golden_path.read_text(encoding="utf-8"))
    request = ModelTicketClassifyInput.model_validate(golden["input"])

    output = await HandlerTicketClassify().handle(request)

    assert isinstance(output, ModelTicketClassifyOutput)
    fresh_json = output.model_dump(mode="json")
    # Full-structure equality AND fingerprint equality (byte-identical output).
    assert fresh_json == golden["output"], (
        f"{golden_path.name}: def-B output structure diverged from recorded def-A"
    )
    assert _fingerprint(fresh_json) == golden["output_sha256"], (
        f"{golden_path.name}: def-B output fingerprint diverged from recorded def-A"
    )


def test_golden_fixture_count_matches_expected_pool() -> None:
    """Regression guard: the recorded scenario pool has a known, reviewed size."""
    assert len(_golden_files()) == _EXPECTED_GOLDEN_COUNT


@pytest.mark.asyncio
async def test_failure_terminal_declared_and_reachable() -> None:
    """State-coverage (OMN-13781): the declared failure terminal is bound and the
    failure path is genuinely reachable.

    The COMPUTE handler emits no events itself — the runtime synthesizes the
    contract's ``runtime_dispatch.terminal_events.failure`` terminal when
    ``handle()`` raises. Here we (1) bind that declared topic to its literal and
    (2) drive a real internal failure (a ``contract_yaml`` whose ``seam_boundaries``
    block omits a required field, so ``ModelSeamBoundaries.model_validate`` raises in
    seam parsing) to prove the failure terminal is not dead.
    """
    contract = yaml.safe_load(_CONTRACT_PATH.read_text(encoding="utf-8"))
    declared_failure = contract["runtime_dispatch"]["terminal_events"]["failure"]
    assert declared_failure == "onex.evt.omnimarket.ticket-classify-failed.v1"

    malformed = ModelTicketClassifyInput(
        correlation_id=UUID("33333333-3333-4333-8333-333333333333"),
        tickets=(
            ModelTicketForClassification(
                ticket_id="OMN-BOOM",
                title="Invalid seam boundaries",
                # consumes item missing the required `module` field -> ValidationError
                contract_yaml=(
                    "seam_boundaries:\n  consumes:\n    - protocol: ProtocolBroken\n"
                ),
            ),
        ),
    )
    with pytest.raises(ValueError, match="Field required"):
        await HandlerTicketClassify().handle(malformed)


def test_fingerprint_discriminates() -> None:
    """The fingerprint oracle is not vacuous: a 1-field perturbation diverges."""
    golden = json.loads(_golden_files()[0].read_text(encoding="utf-8"))
    recorded_fp = golden["output_sha256"]
    assert _fingerprint(golden["output"]) == recorded_fp  # sanity: recompute matches

    perturbed = json.loads(json.dumps(golden["output"]))
    perturbed["total_auto_buildable"] = int(perturbed["total_auto_buildable"]) + 1
    assert _fingerprint(perturbed) != recorded_fp, (
        "fingerprint failed to detect a perturbed output — oracle is vacuous"
    )
