# SPDX-FileCopyrightText: 2026 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

r"""OMN-15597 AC5 — the census corpus, pinned and committed (lane G2).

GENERATED DATA, DO NOT HAND-EDIT. Regeneration recipe at the bottom of this
docstring.

AC5 reads "re-running the census script against the SAME OCC SHA yields 0
checks in the tokenizer-damage class (from 59)". The first implementation
read a live ``onex_change_control`` WORKING CLONE, so it (a) skipped on every
hosted runner, where no clone is reachable, and (b) pinned no SHA. The live
corpus moves daily — the identical census against ``1e6b75f8`` (one day of
OCC commits later) returns 63, not 59 — so a live re-run does not re-run the
census the ticket names, and on CI it ran at all. Both are why AC5 carried
zero standing force before lane G2.

The corpus is therefore snapshotted here at the SHA the 59 was measured at.
The strings are verbatim OCC ``check_value``s — the artifact under test —
and must not be paraphrased, shortened or reformatted.

Provenance
----------
repo:  OmniNode-ai/onex_change_control
sha:   9089ffa9338b23fcb2ba0c28780eeea5224663b0
total command ``check_value``s under ``contracts/OMN-*.yaml``: 32564

``TOKENIZER_DAMAGE_CLASS`` — the 59 check_values across
33 contracts that the PRE-FIX guard
(``omnimarket@a637e4a6^``, ``shlex.split`` + leading-assignment skip)
rejected and the fixed guard accepts. That is the ticket's blast-radius
census reproduced exactly: 59 checks / 33 contracts.

``TOKENIZER_DAMAGE_PATH_COMMANDS`` — every command name the FIXED guard
resolves through ``shutil.which`` while clearing that class. The test stubs
``which`` to resolve exactly this set and nothing else, so the assertion is
host-independent (no ``gh``/``jq`` on the runner is not a failure) while
staying a real assertion: a tokenizer regression judges a substitution
FRAGMENT, which is not in this set, so it is rejected and the test fails.

``NO_EVIDENCE_BUILTIN_CANDIDATES`` — every check_value at the same SHA that
mentions one of the seven ``_NO_EVIDENCE_BUILTIN_PREFIXES`` names as a
word. Selected by a GUARD-INDEPENDENT regex over the raw string
(``(?<![\w./-])(declare|export|let|read|readonly|set|unset)(?![\w./-])``), so it is a superset of anything the guard could
classify as prefix-builtin-only: the R2/R3 narrowing has zero exposure iff
none of these is rejected as such.

Regeneration
------------
There is deliberately NO regeneration script. A generator would be a SECOND
implementation of the census oracle, free to drift from the one the
assertions use — the same "two copies of a predicate, one silently stale"
defect this snapshot exists to close. The selectors live once, in
``test_omn_15597_command_substitution_shape_guard.py``, next to the tests
that consume them.

To re-pin, extract the corpus read-only from an OCC clone (no OCC file is
written — AC6)::

    git -C "$OMNI_HOME/onex_change_control" archive <sha> contracts \
      | tar -x -C /tmp/occ_census

then rebuild the three constants with those selectors, enumerating every
``check_type: command`` ``check_value`` under ``contracts/OMN-*.yaml`` via
``_occ_command_check_values``:

* ``TOKENIZER_DAMAGE_CLASS`` — the values that
  ``_pre_fix_invalid_check_value_reason`` (the vendored pre-fix guard)
  REJECTS and the current ``_invalid_check_value_reason`` ACCEPTS.
* ``TOKENIZER_DAMAGE_PATH_COMMANDS`` — the command names the current guard
  resolves through ``shutil.which`` while clearing that class.
* ``NO_EVIDENCE_BUILTIN_CANDIDATES`` — the values matching
  ``_BUILTIN_WORD_RE``, the guard-independent regex over the raw string.

Changing the pin is a deliberate act: the ticket's AC5 number (59 / 33
contracts) is only meaningful at this SHA, and
``test_pinned_corpus_is_the_census_the_ticket_names`` asserts both numbers,
so a re-pin cannot land silently.
"""

from __future__ import annotations

OCC_CENSUS_SHA = "9089ffa9338b23fcb2ba0c28780eeea5224663b0"

OCC_CENSUS_TOTAL_COMMAND_CHECK_VALUES = 32564

OCC_CENSUS_DAMAGE_CLASS_CONTRACT_COUNT = 33

TOKENIZER_DAMAGE_CLASS: dict[str, str] = {
    "OMN-14436.yaml#0": 'A=$(gh api "repos/OmniNode-ai/onex_change_control/contents/scripts/ci/dod_runner_legacy_allowlist.txt?ref=7266a4f1b2fff2bf5a362a60bb1f099dd94d1835" --jq .content 2>/dev/null | base64 -d 2>/dev/null); T=$(printf \'%s\' "$A" | grep -vcE \'^[[:space:]]*#|^[[:space:]]*$\'); B=$(printf \'%s\' "$A" | grep -cE \'^OMN-[0-9]+ [0-9a-f]{64}$\'); test "$T" -gt 0 && test "$T" = "$B" #magic___^_^___line',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14454.yaml#0": "C=$(gh api \"repos/OmniNode-ai/omnibase_infra/contents/.github/workflows/ci.yml?ref=d5da8826a2cc7e5af0f442c0ae2e5c3cd27c1e1c\" --jq .content 2>/dev/null | base64 -d 2>/dev/null); N=$(printf '%s' \"$C\" | grep -cE '^[[:space:]]+needs: \\['); X=$(printf '%s' \"$C\" | grep -E '^[[:space:]]+needs: \\[' | grep -c 'contract-compliance'); test \"$N\" -gt 0 && test \"$X\" -eq 0",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14466.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/.github/workflows/release-drift-monitor.yml?ref=cfe726f88e91c350164e71a3af13823187f38ea9" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -c \'cron:\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -Fc \'release_drift_monitor.py\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -Fc \'PIPESTATUS\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -Fc \'exit "$code"\')" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14466.yaml#1": 'L=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/release_drift_monitor_lib.py?ref=cfe726f88e91c350164e71a3af13823187f38ea9" --jq .content 2>/dev/null | base64 -d 2>/dev/null); DEF=$(printf \'%s\' "$L" | grep -cE \'^def (evaluate_repo|exit_code_for)\\(\'); IO=$(printf \'%s\' "$L" | grep -cE \'^(import|from) (subprocess|urllib|os|requests|httpx)([ .]|$)\'); B=$(printf \'%s\' "$L" | grep -c \'return 2\'); test "$DEF" -ge 2 && test "$IO" -eq 0 && test "$B" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14466.yaml#2": 'S=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/release_drift_monitor.py?ref=cfe726f88e91c350164e71a3af13823187f38ea9" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$S" | grep -c \'onex_state/friction\')" -ge 1 && test "$(printf \'%s\' "$S" | grep -c \'node_friction_triage\')" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14467.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/trigger_rebuild_on_merge.py?ref=f304e13b64e011ee3ae081349178c4f7fd4f99a3" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -c \'require_producer_preconditions\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -cE \'click\\.echo\\([^)]*skipping publish\')" -eq 0',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14470.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnimarket/contents/scripts/trigger_rebuild_on_merge.py?ref=3c6baef160863cbe54304c8d8c85b3f936765701" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -c \'require_producer_preconditions\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -cE \'click\\.echo\\([^)]*skipping publish\')" -eq 0',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14470.yaml#1": 'C=$(gh api "repos/OmniNode-ai/omnimarket/contents/scripts/producer_effect_assertion.py?ref=3c6baef160863cbe54304c8d8c85b3f936765701" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -cE \'class ProducerZeroOutputError|def require_producer_preconditions|def assert_producer_emitted\')" -ge 3 && test "$(printf \'%s\' "$C" | grep -c \'TODO(OMN-14470)\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -cE \'^(import|from) omnibase_infra\')" -eq 0',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#0": "H=$(gh api \"repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/nodes/node_release_identity_compute/handlers/handler_release_identity.py?ref=fe3048daecd61c1f80217c2fcea1feee928f14b4\" --jq .content | base64 -d); printf '%s' \"$H\" | grep -q 'def handle(' && printf '%s' \"$H\" | grep -q 'ModelReleaseIdentityDecision' && ! printf '%s' \"$H\" | grep -q 'ModelEventEnvelope'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#1": "H=$(gh api \"repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/nodes/node_release_identity_compute/handlers/handler_release_identity.py?ref=b30107b73b161f327b3cb6c10858eec81111f288\" --jq .content | base64 -d); printf '%s' \"$H\" | grep -q 'def handle(' && printf '%s' \"$H\" | grep -q 'ModelReleaseIdentityDecision' && ! printf '%s' \"$H\" | grep -q 'ModelEventEnvelope'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#2": 'L=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/docker/runners/runner-image.lock.json?ref=b30107b73b161f327b3cb6c10858eec81111f288" --jq .content | base64 -d); printf \'%s\' "$L" | grep -q \'"shared_env_digest": "98b3d453ba530d1135bf81f3"\' && printf \'%s\' "$L" | grep -q \'"identity_digest": "c4b259aef0791aee9d1fdb1111da632f"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#3": 'B=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/fixtures/dispatch_parity/baseline-selection-v2.json?ref=b30107b73b161f327b3cb6c10858eec81111f288" --jq .content | base64 -d); printf \'%s\' "$B" | grep -q \'"contracts_discovered": 122\' && printf \'%s\' "$B" | grep -q \'"omnibase_infra": 111\' && printf \'%s\' "$B" | grep -q \'"discovery_errors": 0\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#4": "S=$(gh api \"repos/OmniNode-ai/omnibase_infra/contents/scripts/check_release_identity.py?ref=491a1438d820835561e45387b83a4c3b596dee9f\" --jq .content | base64 -d); printf '%s' \"$S\" | grep -q '_SRC_DIR = _REPO_ROOT / \"src\"' && printf '%s' \"$S\" | grep -q 'sys.path.insert(0, str(_SRC_DIR))'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#5": 'T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/scripts/test_check_release_identity.py?ref=491a1438d820835561e45387b83a4c3b596dee9f" --jq .content | base64 -d); printf \'%s\' "$T" | grep -Fq \'env={**_CLEAN_ENV, "PYTHONPATH": str(_REPO_ROOT / "src")}\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14471.yaml#6": 'L=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/docker/runners/runner-image.lock.json?ref=491a1438d820835561e45387b83a4c3b596dee9f" --jq .content | base64 -d); printf \'%s\' "$L" | grep -q \'"shared_env_digest": "98b3d453ba530d1135bf81f3"\' && printf \'%s\' "$L" | grep -q \'"identity_digest": "c4b259aef0791aee9d1fdb1111da632f"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14473.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/.github/workflows/ci.yml?ref=398cddb17ea3a312d6aef51333695998f828f5ed" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -c \'effect-assertion-gate\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -c \'tests/scripts/test_trigger_producer_effect_assertion.py\')" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14473.yaml#1": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/ci/ci_summary_gate.py?ref=398cddb17ea3a312d6aef51333695998f828f5ed" --jq .content 2>/dev/null | base64 -d 2>/dev/null); test "$(printf \'%s\' "$C" | grep -c \'STRICT_GATE_JOBS\')" -ge 1 && test "$(printf \'%s\' "$C" | grep -c \'Effect-Assertion Gate (RT-5)\')" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14486.yaml#0": "H=$(gh api \"repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/runtime/auto_wiring/handler_wiring.py?ref=8c2257002be6ec3c6c9c966281f5dbc07f3f7319\" --jq .content 2>/dev/null | base64 -d 2>/dev/null); P=$(printf '%s' \"$H\" | grep -c 'except StateIoUnconfiguredError'); R=$(printf '%s' \"$H\" | grep -A12 'except StateIoUnconfiguredError' | grep -c '^ *raise$'); test \"$P\" -ge 2 && test \"$R\" -ge 2",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14486.yaml#1": 'T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/unit/runtime/test_handler_wiring_state_io.py?ref=8c2257002be6ec3c6c9c966281f5dbc07f3f7319" --jq .content 2>/dev/null | base64 -d 2>/dev/null); RA=$(printf \'%s\' "$T" | grep -Fc \'pytest.raises(StateIoUnconfiguredError\'); W=$(printf \'%s\' "$T" | grep -Fc \'wire_from_manifest\'); test "$RA" -ge 2 && test "$W" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14504.yaml#0": 'B=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4081 --jq .body); N=$(printf \'%s\' "$B" | grep -c \'Evidence-Ticket: OMN-14504\'); R=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4081 --jq .head.ref); test "$N" -ge 1 && test "$R" = "jonah/omn-14504-occ-infra-2282-pythonpath-shadow"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14509.yaml#0": 'F=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/integration/test_state_io_outbox_seam_red.py?ref=455ca16a57037f9c1360951f1d875d846f36c326" --jq .content | base64 -d); R=$(printf \'%s\' "$F" | grep -c \'def test_redelivery_of_same_input_resumes_publish_from_row_without_rerunning_handler\'); G=$(printf \'%s\' "$F" | grep -c \'def test_e1_guard_causation_and_envelope_ids_must_differ\'); S=$(printf \'%s\' "$F" | grep -c \'"strict": True, "raises": AssertionError\'); X=$(printf \'%s\' "$F" | grep -c \'@pytest.mark.xfail\'); C=$(printf \'%s\' "$F" | grep -c \'causation_envelope_id\'); test "$R" -ge 1 && test "$G" -ge 1 && test "$S" -ge 1 && test "$X" -ge 6 && test "$C" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14509.yaml#1": "SRC=$(gh api \"repos/OmniNode-ai/omnibase_infra/pulls/2284/files\" --paginate --jq '.[].filename' | grep '^src/' | wc -l | tr -d ' '); RED=$(gh api \"repos/OmniNode-ai/omnibase_infra/pulls/2284/files\" --paginate --jq '.[].filename' | grep 'tests/integration/test_state_io_outbox_seam_red.py' | wc -l | tr -d ' '); test \"$SRC\" -eq 0 && test \"$RED\" -ge 1",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14509.yaml#2": "B=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4071 --jq .body); N=$(printf '%s' \"$B\" | grep -c 'Evidence-Source: OmniNode-ai/omnibase_infra#2284'); T=$(printf '%s' \"$B\" | grep -c 'Evidence-Ticket: OMN-14509'); test \"$N\" -ge 1 && test \"$T\" -ge 1",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14509.yaml#3": 'B=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4075 --jq .body); N=$(printf \'%s\' "$B" | grep -c \'Evidence-Source: OmniNode-ai/omnibase_infra#2284\'); T=$(printf \'%s\' "$B" | grep -c \'Evidence-Ticket: OMN-14509\'); R=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4075 --jq .head.ref); test "$N" -ge 1 && test "$T" -ge 1 && test "$R" = "jonah/omn-14509-rebind-infra-2284"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14516.yaml#0": 'S=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/runtime/service_kernel.py?ref=5f64390c3d703d328ecd46fc04aba0757dbacb84" --jq .content | base64 -d); H=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/nodes/node_ledger_projection_compute/handlers/handler_ledger_projection.py?ref=5f64390c3d703d328ecd46fc04aba0757dbacb84" --jq .content | base64 -d); E=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/runtime/intent_effects/intent_effect_ledger_append.py?ref=5f64390c3d703d328ecd46fc04aba0757dbacb84" --jq .content | base64 -d); K=$(printf \'%s\' "$S" | grep -c \'auto_wiring_result_appliers\\["node_ledger_projection_compute"\\]\'); R=$(printf \'%s\' "$S" | grep -c \'"ledger.append"\'); D=$(printf \'%s\' "$H" | grep -c \'async def handle(\'); C=$(printf \'%s\' "$H" | grep -c \'_coerce_event_message\'); I=$(printf \'%s\' "$E" | grep -c \'class IntentEffectLedgerAppend\'); test "$K" -ge 1 && test "$R" -ge 1 && test "$D" -ge 1 && test "$C" -ge 1 && test "$I" -ge 1',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14548.yaml#0": 'B=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4093 --jq .body); N=$(printf \'%s\' "$B" | grep -c \'Evidence-Ticket: OMN-14548\'); R=$(gh api repos/OmniNode-ai/onex_change_control/pulls/4093 --jq .head.ref); test "$N" -ge 1 && test "$R" = "jonah/omn-14548-occ-boundary-dlq"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14587.yaml#0": 'test "$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/ci/canonical_handler_shape_baseline.py?ref=daeba34583fd4d3bc08dc738832bcf1a182fc72c" --jq .content | base64 -d | grep -cE \'^\\s+"omnibase_infra\\.nodes\\.\')" -eq 93',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14587.yaml#1": 'test "$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/ci/canonical_handler_shape_baseline.py?ref=d37ebb6372d507f33200ec2c283304cbb7bb22a2" --jq .content | base64 -d | grep -cE \'^\\s+"omnibase_infra\\.nodes\\.\')" -eq 92',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14587.yaml#2": 'test "$(gh api "repos/OmniNode-ai/omnibase_infra/contents/scripts/ci/canonical_handler_shape_baseline.py?ref=28e6780c342269da6e9057d04d58c68a6bea8c90" --jq .content | base64 -d | grep -cE \'^\\s+"omnibase_infra\\.nodes\\.\')" -eq 92',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14714.yaml#0": 'out=$(gh api "repos/OmniNode-ai/omnimarket/contents/src/omnimarket/nodes/node_occ_companion_compute/handlers/handler_occ_companion_compute.py?ref=0747500e682c903301bc1bd9eb56578c6dad72af" --jq .content | base64 -d) && test -n "$out" && ! printf \'%s\' "$out" | grep -qE \'^[[:space:]]+width=1_000_000,$\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14714.yaml#1": "out=$(gh api \"repos/OmniNode-ai/omnimarket/contents/tests/unit/nodes/node_occ_companion_compute/test_occ_emitter_golden_fixtures_omn_14710.py?ref=0747500e682c903301bc1bd9eb56578c6dad72af\" --jq .content | base64 -d) && test -n \"$out\" && printf '%s' \"$out\" | grep -q 'def test_merged_path_supersession_is_yamlfmt_clean' && ! printf '%s' \"$out\" | grep -B6 'def test_merged_path_supersession_is_yamlfmt_clean' | grep -q 'pytest.mark.xfail'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14980.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/aws/cluster-dev/push_validation_bundles_s3.tf?ref=9e2fee7cfade59442404d7542d868875f7b40af8') && printf '%s' \"$body\" | grep -qF 'PUSH-VALIDATION BUNDLE TRANSFER S3' && ! printf '%s' \"$body\" | grep -qF 'push_validation_bundle_writer'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15142.yaml#0": "(gh api 'repos/OmniNode-ai/omnibase_infra/contents/scripts/deploy-runners.sh?ref=81407bcb0ae4f1c1d4215637d01ab9000edc3238' --jq .content | base64 -d | grep -q 'DEPLOY_RUNNER_OMNI_HOME') && (gh api 'repos/OmniNode-ai/omnibase_infra/contents/scripts/deploy-runners.sh?ref=81407bcb0ae4f1c1d4215637d01ab9000edc3238' --jq .content | base64 -d | grep -q 'DEPLOY_RUNNER_TOKEN') && (gh api 'repos/OmniNode-ai/omnibase_infra/contents/scripts/deploy-runners.sh?ref=81407bcb0ae4f1c1d4215637d01ab9000edc3238' --jq .content | base64 -d | grep -q 'DEPLOY_RUNNER_OPERATOR_ENV_FILE  Host path of the operator env file')",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15192.yaml#0": 'AS="$(gh api graphql --paginate -f query=\'query($endCursor:String){ search(query:"repo:OmniNode-ai/onex_change_control is:pr label:\\"occ:machine-minted\\" in:title \\"OCC companion for OmniNode-ai\\" created:>2026-07-29T03:01:01Z", type:ISSUE, first:100, after:$endCursor) { pageInfo{hasNextPage endCursor} nodes { ... on PullRequest { number timelineItems(itemTypes:[HEAD_REF_FORCE_PUSHED_EVENT], first:50) { nodes { ... on HeadRefForcePushedEvent { actor { login } } } } } } } }\' --jq \'.data.search.nodes[].timelineItems.nodes[].actor.login\' | sort -u | paste -sd, -)" && [ "$AS" = "jonahgabriel,onexbot-occ-writer" ]',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15192.yaml#1": 'CB="$(gh api graphql --paginate -f query=\'query($endCursor:String){ search(query:"repo:OmniNode-ai/onex_change_control is:pr label:\\"occ:machine-minted\\" in:title \\"OCC companion for OmniNode-ai\\" created:>2026-07-29T03:01:01Z", type:ISSUE, first:100, after:$endCursor) { pageInfo{hasNextPage endCursor} nodes { ... on PullRequest { number timelineItems(itemTypes:[HEAD_REF_FORCE_PUSHED_EVENT], first:50) { nodes { ... on HeadRefForcePushedEvent { actor { login } } } } } } } }\' --jq \'.data.search.nodes[]|.number as $n|.timelineItems.nodes[]|[$n,.actor.login]|@tsv\' | sort -u | awk -F\'\\t\' \'{ c[$1]++ } END { for (k in c) if (c[k]>1) print k }\' | sort -n | paste -sd, -)" && [ "$CB" = "5466" ]',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15192.yaml#2": 'EV="$(gh api graphql --paginate -f query=\'query($endCursor:String){ search(query:"repo:OmniNode-ai/onex_change_control is:pr label:\\"occ:machine-minted\\" in:title \\"OCC companion for OmniNode-ai\\" created:>2026-07-29T03:01:01Z", type:ISSUE, first:100, after:$endCursor) { pageInfo{hasNextPage endCursor} nodes { ... on PullRequest { number timelineItems(itemTypes:[HEAD_REF_FORCE_PUSHED_EVENT], first:50) { nodes { ... on HeadRefForcePushedEvent { actor { login } } } } } } } }\' --jq \'.data.search.nodes[].timelineItems.nodes[].actor.login\' | awk \'END { print NR+0 }\')" && [ "$EV" -ge 55 ]',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && Y=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_canary_catalog_namespace.yaml?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); names={n.id for n in ast.walk(t) if isinstance(n,ast.Name)}; assert "build_canary_catalog_from_candidate" in names, "checker does not build the catalog via build_canary_catalog_from_candidate"; assert "load_canary_namespace" in names, "checker does not load the namespace YAML via load_canary_namespace"; doc={id(n.value) for n in ast.walk(t) if isinstance(n,ast.Expr) and isinstance(n.value,ast.Constant)}; bad=[n.value for n in ast.walk(t) if isinstance(n,ast.Constant) and isinstance(n.value,str) and id(n) not in doc and n.value.startswith("onex.")]; assert not bad, "checker hardcodes catalog/topic literals instead of deriving them: %r" % (bad,)\' && printf \'%s\\n\' "$Y" | grep -q \'^epoch: "mstg1"$\' && printf \'%s\\n\' "$Y" | grep -q \'^topic_prefix: "onex.mstg1."$\' && printf \'%s\\n\' "$Y" | grep -q \'^group_prefix: "onex.mstg1."$\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#1": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); mut=sorted({f.name for f in ast.walk(t) if isinstance(f,(ast.FunctionDef,ast.AsyncFunctionDef)) and any(isinstance(n,ast.Attribute) and n.attr in ("create_topics","delete_topics","alter_configs") for n in ast.walk(f))}); assert mut==["create_missing_catalog_topics"], "broker mutation outside the opt-in helper: %r" % (mut,); calls=[c for c in ast.walk(t) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id=="create_missing_catalog_topics"]; assert len(calls)==1, "expected exactly one create_missing_catalog_topics call site, got %d" % len(calls); guard=[i for i in ast.walk(t) if isinstance(i,ast.If) and "create_missing" in ast.dump(i.test) and any(c.id=="create_missing_catalog_topics" for c in ast.walk(i) if isinstance(c,ast.Name))]; assert guard, "create_missing_catalog_topics call site is not guarded by args.create_missing"; flags=[c for c in ast.walk(t) if isinstance(c,ast.Call) and isinstance(c.func,ast.Attribute) and c.func.attr=="add_argument" and any(isinstance(a,ast.Constant) and a.value=="--create-missing" for a in c.args)]; assert len(flags)==1, "--create-missing is not declared exactly once"; kw={k.arg:k.value for k in flags[0].keywords}; assert isinstance(kw.get("default"),ast.Constant) and kw["default"].value is False, "--create-missing default is not False (check-only is not the default)"; assert isinstance(kw.get("action"),ast.Constant) and kw["action"].value=="store_true", "--create-missing is not an opt-in store_true flag"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#2": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && A=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/event_bus/kafka_auth.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns=[f for f in ast.walk(t) if isinstance(f,(ast.FunctionDef,ast.AsyncFunctionDef)) and f.name=="open_admin_client"]; assert len(fns)==1, "open_admin_client missing from the checker"; f=fns[0]; assert any(isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id=="build_aiokafka_auth_kwargs_from_env" for c in ast.walk(f)), "checker does not call the shared build_aiokafka_auth_kwargs_from_env"; adm=[c for c in ast.walk(f) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id=="AIOKafkaAdminClient"]; assert len(adm)==1, "AIOKafkaAdminClient not constructed exactly once"; assert any(k.arg is None for k in adm[0].keywords), "auth kwargs are not splatted into AIOKafkaAdminClient"\' && printf \'%s\' "$A" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns={f.name for f in ast.walk(t) if isinstance(f,(ast.FunctionDef,ast.AsyncFunctionDef))}; assert "build_aiokafka_auth_kwargs_from_env" in fns, "producer side of the kafka auth kwargs seam is missing"; f=[x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef)) and x.name=="build_aiokafka_auth_kwargs"][0]; br=[i for i in ast.walk(f) if isinstance(i,ast.If) and "AWS_MSK_IAM" in ast.dump(i.test)]; assert br, "no AWS_MSK_IAM branch in the kwargs builder"; d=ast.dump(br[0]); assert "OAUTHBEARER" in d, "AWS_MSK_IAM branch does not set sasl_mechanism=OAUTHBEARER"; assert "sasl_oauth_token_provider" in d, "AWS_MSK_IAM branch sets no sasl_oauth_token_provider"; assert "MSKTokenProvider" in d, "AWS_MSK_IAM branch does not use MSKTokenProvider"; assert "SASL_SSL" in d, "AWS_MSK_IAM branch does not fail closed on security_protocol"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#3": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys,re; t=ast.parse(sys.stdin.read()); d=ast.get_docstring(t) or ""; n=re.sub(r"\\s+"," ",d); assert "Live execution against the actual MSK cluster is the AWS lane" in n and "out of CI scope here." in n, "module docstring does not carry the live-MSK-run exclusion"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#4": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/unit/topics/test_managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); names={n.id for n in ast.walk(t) if isinstance(n,ast.Name)}; assert "build_canary_catalog_from_candidate" in names, "checker does not build the catalog via build_canary_catalog_from_candidate"; assert "load_canary_namespace" in names, "checker does not load the namespace YAML via load_canary_namespace"; doc={id(n.value) for n in ast.walk(t) if isinstance(n,ast.Expr) and isinstance(n.value,ast.Constant)}; bad=[n.value for n in ast.walk(t) if isinstance(n,ast.Constant) and isinstance(n.value,str) and id(n) not in doc and n.value.startswith("onex.")]; assert not bad, "checker hardcodes catalog/topic literals instead of deriving them: %r" % (bad,)\' && printf \'%s\' "$T" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns=[x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef)) and x.name=="test_diff_topic_set_matches_catalog_topic_names"]; assert len(fns)==1, "executable catalog-parity test test_diff_topic_set_matches_catalog_topic_names is absent at this SHA"; f=fns[0]; s=lambda n: isinstance(n,ast.Call) and isinstance(n.func,ast.Name) and n.func.id=="set"; eq=[c for c in ast.walk(f) if isinstance(c,ast.Compare) and len(c.ops)==1 and isinstance(c.ops[0],ast.Eq) and s(c.left) and s(c.comparators[0]) and "missing_topics" in ast.dump(c.left) and "topic_names" in ast.dump(c.comparators[0])]; assert eq, "parity test does not assert set(diff.missing_topics) == set(catalog.topic_names)"; calls={c.func.id for c in ast.walk(f) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; assert "build_topic_diff" in calls and "build_canary_catalog_from_candidate" in calls, "parity test does not drive the real builder+diff seam: %r" % (sorted(calls),)\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#5": 'T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/unit/topics/test_managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$T" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns={x.name:x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef))}; req=["test_check_only_run_makes_zero_admin_mutation_calls","test_open_admin_client_passes_msk_iam_auth_kwargs","test_out_of_catalog_name_is_reported_not_touched","test_create_missing_catalog_topics_never_touches_out_of_catalog_name"]; missing=[n for n in req if n not in fns]; assert not missing, "in-ticket acceptance tests absent at this SHA: %r" % (missing,); z=fns["test_check_only_run_makes_zero_admin_mutation_calls"]; zc={c.func.id for c in ast.walk(z) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; za={a.attr for a in ast.walk(z) if isinstance(a,ast.Attribute)}; assert "_run" in zc, "zero-mutation test does not drive _run (the artifact that runs)"; assert "AsyncMock" in zc, "zero-mutation test uses no async test double to capture admin calls"; assert {"create_topics","delete_topics"} <= za and "assert_not_called" in za, "zero-mutation test does not capture-and-assert create_topics/delete_topics were never called"; assert any(isinstance(c,ast.Call) and isinstance(c.func,ast.Attribute) and c.func.attr=="parse_args" and c.args and isinstance(c.args[0],ast.List) and not c.args[0].elts for c in ast.walk(z)), "zero-mutation test does not exercise the unflagged (no --create-missing) default"; i=fns["test_open_admin_client_passes_msk_iam_auth_kwargs"]; d=ast.dump(i); ic={c.func.id for c in ast.walk(i) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; assert "open_admin_client" in ic, "IAM test does not call open_admin_client"; assert "KAFKA_SASL_MECHANISM" in d and "AWS_MSK_IAM" in d, "IAM test does not set KAFKA_SASL_MECHANISM=AWS_MSK_IAM"; assert "OAUTHBEARER" in d and "SASL_SSL" in d and "MSKTokenProvider" in d, "IAM test does not assert the OAUTHBEARER/SASL_SSL/MSKTokenProvider kwargs shape"; n=ast.dump(fns["test_create_missing_catalog_topics_never_touches_out_of_catalog_name"])+ast.dump(fns["test_out_of_catalog_name_is_reported_not_touched"]); assert "create_missing_catalog_topics" in n and "out_of_catalog_topics" in n, "negative-control tests do not bind the out-of-catalog stray-name path"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15299.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/.github/workflows/terraform-plan.yml?ref=a9ca9f4ab6403a76266bad681f38f17ad2917eb1') && printf '%s' \"$body\" | grep -qF 'name: Terraform Plan (PR Check)' && ! printf '%s' \"$body\" | grep -qF 'Assert the matrix root actually contains terraform'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15301.yaml#0": 'd=$(mktemp -d) && gh run download 30347509136 --repo OmniNode-ai/omnibase_infra -n build-manifest-candidate-candidate-416b7b9-20260728094011 -D "$d" && jq -e \'.image_digest == "sha256:1c4e306268290df9c378a8ec5973b9c0eaeb8cf094db2923b52ff4c68272fb03" and .commit_sha == "416b7b9945b6e1f7135a7befe7ea7f4f3668704d" and .image_tag == "candidate-416b7b9-20260728094011" and .workflow_run_id == "30347509136" and .prod_pinnable == false\' "$d/build-manifest.json" >/dev/null; rc=$?; rm -rf "$d"; exit $rc',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15328.yaml#0": 'd=$(mktemp -d) && gh run download 30347509136 --repo OmniNode-ai/omnibase_infra -n build-manifest-candidate-candidate-416b7b9-20260728094011 -D "$d" && jq -e \'.image_digest == "sha256:1c4e306268290df9c378a8ec5973b9c0eaeb8cf094db2923b52ff4c68272fb03" and .commit_sha == "416b7b9945b6e1f7135a7befe7ea7f4f3668704d" and .image_tag == "candidate-416b7b9-20260728094011" and .workflow_run_id == "30347509136" and .prod_pinnable == false\' "$d/build-manifest.json" >/dev/null; rc=$?; rm -rf "$d"; exit $rc',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15365.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/docker/onex-api/workflow_contracts.py?ref=ba51bcd33cd59affd02d8458efcce741d8abc839') && printf '%s' \"$body\" | grep -qF 'Workflow contract registry' && ! printf '%s' \"$body\" | grep -qF 'declared but fenced'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15366.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/k8s/onex-dev/runtime/kustomization.yaml?ref=93ed78dd496d6149fedddfcc4468df06c317a18a') && printf '%s' \"$body\" | grep -qF 'apiVersion: kustomize.config.k8s.io/v1beta1' && ! printf '%s' \"$body\" | grep -qF 'sha256:48673cb7af04bc010b04eece5c5f6c8c71bbd5e004e99936fcec3508d95287b7'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15370.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/k8s/onex-dev/omniweb/deployment.yaml?ref=2af36af0fbd3e1c631495ea46c69b327081c7b2a') && printf '%s' \"$body\" | grep -qF 'name: omniweb' && ! printf '%s' \"$body\" | grep -qF 'https://dev.api.omninode.ai'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15375.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/aws/cluster-dev/push_validation_bundles_s3.tf?ref=ae400c5cd21b21fa9f3e962a2229dd7abf2f10d6') && printf '%s' \"$body\" | grep -qF 'PUSH-VALIDATION BUNDLE TRANSFER S3' && ! printf '%s' \"$body\" | grep -qF 'CORRECTED UNDER OMN-15375'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15376.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omnibase_infra/contents/docker/migrations/forward/nodes/node_projection_baselines/0001_create_baselines_tables.sql?ref=11b460db23d40dd2ca7704d0c3e9fd89851af60c') && printf '%s' \"$body\" | grep -qF 'OMN-11887: node-owned projection migration' && ! printf '%s' \"$body\" | grep -qF 'ALTER TABLE baselines_snapshots ADD COLUMN IF NOT EXISTS snapshot_id'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15376.yaml#1": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omnibase_infra/contents/docker/migrations/forward/nodes/node_projection_cost_summary/0001_create_llm_cost_aggregates.sql?ref=11b460db23d40dd2ca7704d0c3e9fd89851af60c') && printf '%s' \"$body\" | grep -qF 'node-owned projection migration' && ! printf '%s' \"$body\" | grep -qF 'ADD COLUMN IF NOT EXISTS aggregation_key'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15383.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omninode_infra/contents/scripts/repair-managed-postgres-ownership.sh?ref=a0639ce48e12b0c0be069d4053299e1b29e1121e') && printf '%s' \"$body\" | grep -qF 'Repair per-service table ownership in a managed PostgreSQL database' && ! printf '%s' \"$body\" | grep -qF 'INCLUDE_PEER_OWNED'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15391.yaml#0": "body=$(gh api -H 'Accept: application/vnd.github.raw' 'repos/OmniNode-ai/omnibase_infra/contents/docker/migrations/forward/nodes/node_projection_baselines/0001_create_baselines_tables.sql?ref=11b460db23d40dd2ca7704d0c3e9fd89851af60c') && printf '%s' \"$body\" | grep -qF 'OMN-11887: node-owned projection migration' && ! printf '%s' \"$body\" | grep -qF 'ALTER TABLE baselines_snapshots ADD COLUMN IF NOT EXISTS snapshot_id'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15484.yaml#0": "out=\"$(gh api 'repos/OmniNode-ai/omnibase_infra/actions/runs/30565261108/attempts/1/jobs' --jq '.jobs[]|select(.name==\"merge-hold-gate / evaluate\")|.conclusion')\" && printf '%s\\n' \"$out\" | grep -qx success",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15484.yaml#1": "out=\"$(gh api 'repos/OmniNode-ai/omnibase_infra/actions/runs/30565261108/attempts/1/jobs' --jq '.jobs[]|select(.name==\"occ-preflight / eligibility\")|.conclusion')\" && printf '%s\\n' \"$out\" | grep -qx failure",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15490.yaml#0": 'state="$(gh pr view 237 --repo jonahgabriel/steel_onslaught --json state,mergeCommit --jq \'.state + " " + (.mergeCommit.oid // "none")\')" && test "$state" = "MERGED e3dbd0171709d9cdd9fb80c4df6b85688a398803"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15493.yaml#0": 'state="$(gh pr view 236 --repo jonahgabriel/steel_onslaught --json state,mergeCommit --jq \'.state + " " + (.mergeCommit.oid // "none")\')" && test "$state" = "MERGED d2a5d9aaeddbf71039d34820bb568e5c9d4561be"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15529.yaml#0": "body=$(gh api 'repos/OmniNode-ai/omnibase_infra/contents/docker/docker-compose.infra.yml?ref=f18d903ca2370c373e5192c0193d4dc6b45ebf24' --jq '.content' | base64 -d) && printf '%s' \"$body\" | grep -qF 'x-runtime-env' && printf '%s' \"$body\" | grep -qF 'ONEXBOT_OCC_PRIVATE_KEY'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15535.yaml#0": 'state="$(gh pr view 239 --repo jonahgabriel/steel_onslaught --json state,mergeCommit --jq \'.state + " " + (.mergeCommit.oid // "none")\')" && test "$state" = "MERGED 4bae73ea51a4f3d42d24ccdcaf68d9ab61d1a9a5"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
}

TOKENIZER_DAMAGE_PATH_COMMANDS: frozenset[str] = frozenset(["gh", "printf", "test"])

NO_EVIDENCE_BUILTIN_CANDIDATES: dict[str, str] = {
    "OMN-10284.yaml#0": "grep -cE 'export (interface|type) (BarChartFieldMapping|TrendChartFieldMapping|KPITileMetricConfig|DataTableColumnConfig|EmptyStateConfig|EmptyStateReason)' omnidash/shared/types/chart-config.ts",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-10288.yaml#0": "grep -q 'export const Empty' src/components/charts/threejs/KPITileCluster.stories.tsx",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-10288.yaml#1": "grep -q 'export const Populated' src/components/charts/threejs/KPITileCluster.stories.tsx",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-10289.yaml#0": "grep -F 'export const Empty' src/components/charts/threejs/DataTable.stories.tsx && grep -F 'export const Populated' src/components/charts/threejs/DataTable.stories.tsx",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-10485.yaml#0": "grep -q '^status: PASS$' drift/dod_receipts/OMN-10485/dod-004/command.yaml && grep -q '^  pull-requests: read$' .github/workflows/call-occ-preflight.yml",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-11168.yaml#0": "grep -q '^status: PASS$' \"drift/dod_receipts/OMN-11168/dod-playwright-secret-blocker/command.yaml\" && grep -q 'E2E_TEST_PASSWORD must be set in CI' \"drift/dod_receipts/OMN-11168/dod-playwright-secret-blocker/command.yaml\" && grep -q 'no E2E secrets or variables configured' \"drift/dod_receipts/OMN-11168/dod-playwright-secret-blocker/command.yaml\"",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-11743.yaml#0": "grep -q '^status: PASS$' \"drift/dod_receipts/OMN-11743/dod-git-credential-setup-classified/command.yaml\" && grep -q '26342924695' \"drift/dod_receipts/OMN-11743/dod-git-credential-setup-classified/command.yaml\" && grep -q 'could not read Username' \"drift/dod_receipts/OMN-11743/dod-git-credential-setup-classified/command.yaml\"",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-12532.yaml#0": "grep -q '^status: PASS$' \"$CONTRACT_REPO_DIR/drift/dod_receipts/OMN-12532/dod-stability-dogfood/command.yaml\" && grep -q 'ONEX_STATE_DIR is not set' \"$CONTRACT_REPO_DIR/drift/dod_receipts/OMN-12532/dod-stability-dogfood/command.yaml\" && grep -q 'correlation_id: 2a36f868-4153-46b7-992a-5f3e806c7a2a' \"$CONTRACT_REPO_DIR/drift/dod_receipts/OMN-12532/dod-stability-dogfood/command.yaml\" && grep -q 'rpk topic produce' \"$CONTRACT_REPO_DIR/drift/dod_receipts/OMN-12532/dod-stability-dogfood/command.yaml\"",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-12592.yaml#0": "python3 - <<'PY'\nfrom pathlib import Path\ntext = Path('.github/required-checks.yaml').read_text()\nrequired = {'verify / verify', 'occ-preflight / eligibility', 'required-check-skip-guard / check-skip-vectors'}\nmissing = sorted(required - set(x for x in required if x in text))\nif missing:\n    raise SystemExit(f'missing required contexts: {missing}')\nPY",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14485.yaml#0": 't="$(mktemp)" && gh api "repos/OmniNode-ai/omnimarket/contents/src/omnimarket/nodes/node_delegate_skill_orchestrator/contract.yaml?ref=bf6290eb3c06686c6a4071ac67e95eaacd250fcb" --jq .content | base64 -d > "$t" && grep -F -- \'declare the tenant seam on the RESPONSE/terminal side\' "$t" && grep -F -- \'delegation_events.tenant_id\' "$t"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14494.yaml#0": 'PRODUCT_PR_NUMBER=1767; PRODUCT_REPO=OmniNode-ai/omnimarket; PRODUCT_HEAD=8f8c8225f32823edbc6e686adf50a87011c87f73; d="$(mktemp -d)" && gh pr view "$PRODUCT_PR_NUMBER" --repo "$PRODUCT_REPO" --json headRefOid,baseRefName,files,title --jq \'.headRefOid + "\\n" + .baseRefName + "\\n" + .title + "\\n" + ((.files | map(.path)) | join("\\n"))\' > "$d/pr.txt" && grep -Fq "$PRODUCT_HEAD" "$d/pr.txt" && grep -Fxq dev "$d/pr.txt" && grep -Fq \'fix(OMN-14494): declare dlq_topics on node_projection_delegation_inference_response\' "$d/pr.txt" && for p in src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py; do grep -Fq "$p" "$d/pr.txt" && mkdir -p "$d/$(dirname "$p")" && gh api "repos/${PRODUCT_REPO}/contents/${p}?ref=${PRODUCT_HEAD}" --jq .content | base64 --decode > "$d/$p"; done && grep -Fq \'dlq_topics:\' "$d/src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml" && grep -Fq \'onex.dlq.omnimarket.projection-delegation-inference-response-malformed.v1\' "$d/src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml" && grep -Fq \'test_contract_declares_dlq_topic\' "$d/tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py" && grep -Fq \'test_dlq_topic_follows_onex_dlq_naming_convention\' "$d/tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14494.yaml#1": 'PRODUCT_PR_NUMBER=1767; PRODUCT_REPO=OmniNode-ai/omnimarket; PRODUCT_HEAD=fd0395e9dc55be2f042e1a3084bb5f7f1e9373a5; d="$(mktemp -d)" && gh pr view "$PRODUCT_PR_NUMBER" --repo "$PRODUCT_REPO" --json headRefOid,baseRefName,files,title --jq \'.headRefOid + "\\n" + .baseRefName + "\\n" + .title + "\\n" + ((.files | map(.path)) | join("\\n"))\' > "$d/pr.txt" && grep -Fq "$PRODUCT_HEAD" "$d/pr.txt" && grep -Fxq dev "$d/pr.txt" && grep -Fq \'fix(OMN-14494): declare dlq_topics on node_projection_delegation_inference_response\' "$d/pr.txt" && for p in src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py src/omnimarket/nodes/node_codegen_outcome_reducer/contract.yaml tests/nodes/node_codegen_outcome_reducer/test_codegen_outcome_reducer.py; do grep -Fq "$p" "$d/pr.txt" && mkdir -p "$d/$(dirname "$p")" && gh api "repos/${PRODUCT_REPO}/contents/${p}?ref=${PRODUCT_HEAD}" --jq .content | base64 --decode > "$d/$p"; done && grep -Fq \'dlq_topics:\' "$d/src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml" && grep -Fq \'onex.dlq.omnimarket.projection-delegation-inference-response-malformed.v1\' "$d/src/omnimarket/nodes/node_projection_delegation_inference_response/contract.yaml" && grep -Fq \'test_contract_declares_dlq_topic\' "$d/tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py" && grep -Fq \'test_dlq_topic_follows_onex_dlq_naming_convention\' "$d/tests/nodes/node_projection_delegation_inference_response/test_node_projection_delegation_inference_response_contract.py" && grep -Fq \'never imports the runtime envelope type\' "$d/src/omnimarket/nodes/node_codegen_outcome_reducer/contract.yaml" && grep -Fq \'never the untyped runtime wrapper\' "$d/src/omnimarket/nodes/node_codegen_outcome_reducer/contract.yaml" && grep -Fq \'never the untyped runtime wrapper\' "$d/tests/nodes/node_codegen_outcome_reducer/test_codegen_outcome_reducer.py" && ! grep -Fq \'ModelEventEnvelope\' "$d/src/omnimarket/nodes/node_codegen_outcome_reducer/contract.yaml" && ! grep -Fq \'raw envelope\' "$d/tests/nodes/node_codegen_outcome_reducer/test_codegen_outcome_reducer.py"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14505.yaml#0": 'd="$(mktemp -d)" && gh api "repos/OmniNode-ai/omniclaude/contents/.github/actions/deploy-gate/validate_pr_deploy_required.py?ref=c69a565cb8681107c780791be366ef61c61c49f4" --jq .content | base64 -d > "$d/v.py" && DEPLOY_GATE_FALSIFIABILITY=enforce python3 -c \'\nimport importlib.util, sys, pathlib\nd = pathlib.Path(sys.argv[1])\nspec = importlib.util.spec_from_file_location("v", d / "v.py")\nm = importlib.util.module_from_spec(spec); sys.modules["v"] = m; spec.loader.exec_module(m)\ndef contract(name, cv):\n    p = d / (name + ".yaml")\n    p.write_text("dod_evidence:\\n  - id: x\\n    checks:\\n      - check_value: " + repr(cv) + "\\n")\n    return p\n# Receipt-tree prefix built via concatenation, not a literal contiguous substring,\n# so this PRODUCT-OBSERVING check (gh-api-fetches omniclaude at a pinned SHA and\n# asserts against the fetched code) is not misclassified by OCCs OMN-14436\n# inert-check scanner as a self-referential OCC-store read. This fixture EMBEDS\n# the path as DATA (the exact vacuous value #4067 used), not as a filesystem\n# read in this runner CWD.\n_DR = "drift/" + "dod_receipts/"\nVACUOUS = ("grep -q \\"^status: PASS$\\" " + _DR + "OMN-14487/dod-deploy-assessment-head-f973c737/command.yaml "\n           "&& grep -qi \\"no live deploy\\" " + _DR + "OMN-14487/dod-deploy-assessment-head-f973c737/command.yaml")\nREAL = "docker exec ${RUNTIME_CONTAINER:-omninode-runtime} python -c \\"import omnimarket; print(1)\\""\nEMBED = "echo \\"docker exec\\" && grep -q PASS my_own_receipt"\nvac = m.has_deploy_evidence(contract("OMN-14487", VACUOUS))\nreal = m.has_deploy_evidence(contract("OMN-10124", REAL))\nembed = m.has_deploy_evidence(contract("OMN-EMBED", EMBED))\nprint("vacuous(#4067)=%s real(docker exec)=%s embed_trap=%s" % (vac, real, embed))\nassert vac is False, "FIX ABSENT/VACUOUS: #4067 check_value still satisfies deploy-gate"\nassert embed is False, "EMBED TRAP still accepted"\nassert real is True, "FALSE NEGATIVE: genuine docker-exec probe rejected"\nprint("PASS")\n\' "$d"\n',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14515.yaml#0": 'c="$(mktemp)" && v="$(mktemp)" && gh api "repos/OmniNode-ai/omnibase_core/contents/.github/workflows/ci.yml?ref=4ba239da5e8ab3d2e340108d7e5810bc3b8625fd" --jq .content | base64 -d > "$c" && gh api "repos/OmniNode-ai/omnibase_core/contents/src/omnibase_core/validators/pydantic_extra_forbid.py?ref=4ba239da5e8ab3d2e340108d7e5810bc3b8625fd" --jq .content | base64 -d > "$v" && grep -F -- \'  pydantic-extra-forbid:\' "$c" && grep -F -- \'no-noncanonical-lifecycle-classes, pydantic-extra-forbid, spdx-headers]\' "$c" && grep -F -- \'extra_forbid="${{ needs.pydantic-extra-forbid.result }}"\' "$c" && grep -F -- \'[[ "$extra_forbid" == "success" ]]\' "$c" && grep -F -- \'fetch-depth: 0\' "$c" && grep -F -- \'could not read the diff, \' "$v"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14527.yaml#0": 'f="$(mktemp)" && gh api "repos/OmniNode-ai/omnimarket/contents/src/omnimarket/validators/contract_topic_graph.py?ref=cedce469306eab31a69a7e928242339c900de147" --jq .content | base64 -d > "$f" && grep -Fq -- \'"ORPHANED_CONSUMER",\' "$f" && grep -Fq -- \'"ORPHANED_PRODUCER",\' "$f" && grep -Fq -- \'"DECLARED_BUT_UNWIRED",\' "$f" && grep -Fq -- \'"DISCONNECTED_SUBGRAPH",\' "$f" && grep -Fq -- \'Contract graph refuses to run with PYTHONPATH set\' "$f" && b="$(mktemp)" && gh api "repos/OmniNode-ai/omnimarket/contents/src/omnimarket/validators/data/contract_topic_graph_baseline.yaml?ref=cedce469306eab31a69a7e928242339c900de147" --jq .content | base64 -d > "$b" && [ "$(grep -c \'^- \' "$b")" -eq 744 ]',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14529.yaml#0": 'PRODUCT_PR_NUMBER=1749; PRODUCT_REPO=OmniNode-ai/omnimarket; PRODUCT_HEAD=c31d950b35ab42a522a315cd48b10863245db137; gh pr view "${PRODUCT_PR_NUMBER}" --repo "${PRODUCT_REPO}" --json headRefOid,body --jq \'.headRefOid == "\'${PRODUCT_HEAD}\'" and (.body | contains("SELECT count(*) FROM decision_store")) and (.body | contains("0 \u2192 1 \u2192 2 \u2192 3")) and (.body | contains("3 \u2192 4 \u2192 5")) and (.body | contains("full CLI seam proven end-to-end"))\' | grep -qx true && gh api "repos/${PRODUCT_REPO}/commits/${PRODUCT_HEAD}" --jq \'.commit.message\' | grep -Fq \'fix(OMN-14529): declare decision store orchestrator dependencies\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14631.yaml#0": 'PRODUCT_PR_NUMBER=2315; PRODUCT_REPO=OmniNode-ai/omnibase_infra; PRODUCT_HEAD=0ef19799d107bb4dc55e28c558c54effb74cd453; d="$(mktemp -d)" && gh pr view "$PRODUCT_PR_NUMBER" --repo "$PRODUCT_REPO" --json headRefOid,baseRefName,files,title --jq \'.headRefOid + "\\n" + .baseRefName + "\\n" + .title + "\\n" + ((.files | map(.path)) | join("\\n"))\' > "$d/pr.txt" && grep -Fq "$PRODUCT_HEAD" "$d/pr.txt" && grep -Fxq dev "$d/pr.txt" && grep -Fq \'fix(OMN-14631): close proof gap that let workspace builds ship stale config content\' "$d/pr.txt" && for p in docker/Dockerfile.runtime scripts/runtime_build/compute_workspace_provenance.py tests/scripts/test_compute_workspace_provenance_content_parity.py; do grep -Fq "$p" "$d/pr.txt" && mkdir -p "$d/$(dirname "$p")" && gh api "repos/${PRODUCT_REPO}/contents/${p}?ref=${PRODUCT_HEAD}" --jq .content | base64 --decode > "$d/$p"; done && grep -Fq \'def _content_parity_diff\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'importlib.util.find_spec\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'path.relative_to(root)\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'content_diff_files\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'sharing=locked\' "$d/docker/Dockerfile.runtime" && grep -Fq \'test_tracked_files_root_nested_under_dot_venv_ancestor_is_still_hashed\' "$d/tests/scripts/test_compute_workspace_provenance_content_parity.py" && grep -Fq \'test_main_fails_closed_on_real_drift_when_installed_under_dot_venv_ancestor\' "$d/tests/scripts/test_compute_workspace_provenance_content_parity.py"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14631.yaml#1": 'PRODUCT_PR_NUMBER=2315; PRODUCT_REPO=OmniNode-ai/omnibase_infra; PRODUCT_HEAD=461f1af71c41d5df97a6b62af128b639eefcf889; d="$(mktemp -d)" && gh pr view "$PRODUCT_PR_NUMBER" --repo "$PRODUCT_REPO" --json headRefOid,baseRefName,files,title --jq \'.headRefOid + "\\n" + .baseRefName + "\\n" + .title + "\\n" + ((.files | map(.path)) | join("\\n"))\' > "$d/pr.txt" && grep -Fq "$PRODUCT_HEAD" "$d/pr.txt" && grep -Fxq dev "$d/pr.txt" && grep -Fq \'fix(OMN-14631): close proof gap that let workspace builds ship stale config content\' "$d/pr.txt" && for p in docker/Dockerfile.runtime scripts/runtime_build/compute_workspace_provenance.py tests/scripts/test_compute_workspace_provenance_content_parity.py docker/migrations/forward/nodes/node_projection_baselines_quality/002_realign_quality_snapshots_to_producer_schema.sql docker/migrations/forward/nodes/node_projection_baselines_roi/002_realign_roi_snapshots_to_producer_schema.sql; do grep -Fq "$p" "$d/pr.txt" && mkdir -p "$d/$(dirname "$p")" && gh api "repos/${PRODUCT_REPO}/contents/${p}?ref=${PRODUCT_HEAD}" --jq .content | base64 --decode > "$d/$p"; done && grep -Fq \'def _content_parity_diff\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'importlib.util.find_spec\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'path.relative_to(root)\' "$d/scripts/runtime_build/compute_workspace_provenance.py" && grep -Fq \'sharing=locked\' "$d/docker/Dockerfile.runtime" && grep -Fq \'OMN-14630\' "$d/docker/migrations/forward/nodes/node_projection_baselines_quality/002_realign_quality_snapshots_to_producer_schema.sql" && grep -Fq \'baselines_quality_snapshots\' "$d/docker/migrations/forward/nodes/node_projection_baselines_quality/002_realign_quality_snapshots_to_producer_schema.sql" && grep -Fq \'OMN-14630\' "$d/docker/migrations/forward/nodes/node_projection_baselines_roi/002_realign_roi_snapshots_to_producer_schema.sql" && grep -Fq \'baselines_roi_snapshots\' "$d/docker/migrations/forward/nodes/node_projection_baselines_roi/002_realign_roi_snapshots_to_producer_schema.sql"',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14776.yaml#0": "shellcheck --severity=style scripts/merge-proof && grep -q 'unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE PYTHONPATH' scripts/merge-proof",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-14889.yaml#0": "gh api repos/OmniNode-ai/omnibase_infra/contents/scripts/runtime_build/refresh_dev_lane.sh?ref=3d4dee67ee4413665b0223e2e632fbd3dd2f8f65 --jq .content | base64 -d | grep -q 'readonly LANE=\"dev\"'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#0": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && A=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/event_bus/kafka_auth.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns=[f for f in ast.walk(t) if isinstance(f,(ast.FunctionDef,ast.AsyncFunctionDef)) and f.name=="open_admin_client"]; assert len(fns)==1, "open_admin_client missing from the checker"; f=fns[0]; assert any(isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id=="build_aiokafka_auth_kwargs_from_env" for c in ast.walk(f)), "checker does not call the shared build_aiokafka_auth_kwargs_from_env"; adm=[c for c in ast.walk(f) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id=="AIOKafkaAdminClient"]; assert len(adm)==1, "AIOKafkaAdminClient not constructed exactly once"; assert any(k.arg is None for k in adm[0].keywords), "auth kwargs are not splatted into AIOKafkaAdminClient"\' && printf \'%s\' "$A" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns={f.name for f in ast.walk(t) if isinstance(f,(ast.FunctionDef,ast.AsyncFunctionDef))}; assert "build_aiokafka_auth_kwargs_from_env" in fns, "producer side of the kafka auth kwargs seam is missing"; f=[x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef)) and x.name=="build_aiokafka_auth_kwargs"][0]; br=[i for i in ast.walk(f) if isinstance(i,ast.If) and "AWS_MSK_IAM" in ast.dump(i.test)]; assert br, "no AWS_MSK_IAM branch in the kwargs builder"; d=ast.dump(br[0]); assert "OAUTHBEARER" in d, "AWS_MSK_IAM branch does not set sasl_mechanism=OAUTHBEARER"; assert "sasl_oauth_token_provider" in d, "AWS_MSK_IAM branch sets no sasl_oauth_token_provider"; assert "MSKTokenProvider" in d, "AWS_MSK_IAM branch does not use MSKTokenProvider"; assert "SASL_SSL" in d, "AWS_MSK_IAM branch does not fail closed on security_protocol"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#1": 'C=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/src/omnibase_infra/topics/managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/unit/topics/test_managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$C" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); names={n.id for n in ast.walk(t) if isinstance(n,ast.Name)}; assert "build_canary_catalog_from_candidate" in names, "checker does not build the catalog via build_canary_catalog_from_candidate"; assert "load_canary_namespace" in names, "checker does not load the namespace YAML via load_canary_namespace"; doc={id(n.value) for n in ast.walk(t) if isinstance(n,ast.Expr) and isinstance(n.value,ast.Constant)}; bad=[n.value for n in ast.walk(t) if isinstance(n,ast.Constant) and isinstance(n.value,str) and id(n) not in doc and n.value.startswith("onex.")]; assert not bad, "checker hardcodes catalog/topic literals instead of deriving them: %r" % (bad,)\' && printf \'%s\' "$T" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns=[x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef)) and x.name=="test_diff_topic_set_matches_catalog_topic_names"]; assert len(fns)==1, "executable catalog-parity test test_diff_topic_set_matches_catalog_topic_names is absent at this SHA"; f=fns[0]; s=lambda n: isinstance(n,ast.Call) and isinstance(n.func,ast.Name) and n.func.id=="set"; eq=[c for c in ast.walk(f) if isinstance(c,ast.Compare) and len(c.ops)==1 and isinstance(c.ops[0],ast.Eq) and s(c.left) and s(c.comparators[0]) and "missing_topics" in ast.dump(c.left) and "topic_names" in ast.dump(c.comparators[0])]; assert eq, "parity test does not assert set(diff.missing_topics) == set(catalog.topic_names)"; calls={c.func.id for c in ast.walk(f) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; assert "build_topic_diff" in calls and "build_canary_catalog_from_candidate" in calls, "parity test does not drive the real builder+diff seam: %r" % (sorted(calls),)\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15283.yaml#2": 'T=$(gh api "repos/OmniNode-ai/omnibase_infra/contents/tests/unit/topics/test_managed_staging_topic_checker.py?ref=2e2108f499349c59f851d465185ae90cd08c7980" --jq .content | base64 -d) && printf \'%s\' "$T" | python3 -c \'import ast,sys; t=ast.parse(sys.stdin.read()); fns={x.name:x for x in ast.walk(t) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef))}; req=["test_check_only_run_makes_zero_admin_mutation_calls","test_open_admin_client_passes_msk_iam_auth_kwargs","test_out_of_catalog_name_is_reported_not_touched","test_create_missing_catalog_topics_never_touches_out_of_catalog_name"]; missing=[n for n in req if n not in fns]; assert not missing, "in-ticket acceptance tests absent at this SHA: %r" % (missing,); z=fns["test_check_only_run_makes_zero_admin_mutation_calls"]; zc={c.func.id for c in ast.walk(z) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; za={a.attr for a in ast.walk(z) if isinstance(a,ast.Attribute)}; assert "_run" in zc, "zero-mutation test does not drive _run (the artifact that runs)"; assert "AsyncMock" in zc, "zero-mutation test uses no async test double to capture admin calls"; assert {"create_topics","delete_topics"} <= za and "assert_not_called" in za, "zero-mutation test does not capture-and-assert create_topics/delete_topics were never called"; assert any(isinstance(c,ast.Call) and isinstance(c.func,ast.Attribute) and c.func.attr=="parse_args" and c.args and isinstance(c.args[0],ast.List) and not c.args[0].elts for c in ast.walk(z)), "zero-mutation test does not exercise the unflagged (no --create-missing) default"; i=fns["test_open_admin_client_passes_msk_iam_auth_kwargs"]; d=ast.dump(i); ic={c.func.id for c in ast.walk(i) if isinstance(c,ast.Call) and isinstance(c.func,ast.Name)}; assert "open_admin_client" in ic, "IAM test does not call open_admin_client"; assert "KAFKA_SASL_MECHANISM" in d and "AWS_MSK_IAM" in d, "IAM test does not set KAFKA_SASL_MECHANISM=AWS_MSK_IAM"; assert "OAUTHBEARER" in d and "SASL_SSL" in d and "MSKTokenProvider" in d, "IAM test does not assert the OAUTHBEARER/SASL_SSL/MSKTokenProvider kwargs shape"; n=ast.dump(fns["test_create_missing_catalog_topics_never_touches_out_of_catalog_name"])+ast.dump(fns["test_out_of_catalog_name_is_reported_not_touched"]); assert "create_missing_catalog_topics" in n and "out_of_catalog_topics" in n, "negative-control tests do not bind the out-of-catalog stray-name path"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-15468.yaml#0": "body=\"$(gh api 'repos/OmniNode-ai/omnibase_infra/contents/tests/unit/runtime/test_runtime_local_ingress.py?ref=712ccb070e93bb8de192d466b349c0e7afd6e4b8' --jq .content | base64 -d)\" && printf '%s' \"$body\" | grep -qF 'omnimarket@aea0c33dd89fb82fdca33aac7149992a21c46d43' && printf '%s' \"$body\" | grep -qF '30 of those 51 declare NO top-level' && ! printf '%s' \"$body\" | grep -qF '24 of the 51 contracts declare NO top-level'",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-9637.yaml#0": 'bash -lc \'set -euo pipefail; if git diff --name-only origin/main...HEAD | grep -E "(^|/)Dockerfile$|(^|/)service_kernel\\.py$|(^|/)kernel/|(^|/)auto_wiring/"; then echo "deploy-gate failed: forbidden runtime files changed"; exit 1; fi; echo "deploy-gate: clean \u2014 no forbidden runtime files changed"\'',  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-9860.yaml#0": "uv run python -c \"import yaml; data = yaml.safe_load(open('scripts/ci/test_selection_adjacency.yaml')); assert data.get('schema_version') == 1; assert len(data.get('adjacency', {})) == 38; assert set(data.get('shared_modules', [])).issubset(data.get('adjacency', {}).keys()); print('adjacency ok')\"",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-9865.yaml#0": "uv run python -c \"import yaml; wf=yaml.safe_load(open('.github/workflows/ci.yml').read()); job=wf['jobs']['detect-changes']; assert job['name']=='Detect Changes (shadow)', job['name']; assert job['needs']=='quality-gate', job['needs']; assert set(job['outputs'].keys())=={'is_full_suite','full_suite_reason','split_count','matrix','selected_paths'}, list(job['outputs'].keys()); print('detect-changes job OK')\"",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
    "OMN-9895.yaml#0": "test -f drift/dod_receipts/OMN-9895/dod-guard-pattern/command.yaml && grep -q '^status:.*PASS' drift/dod_receipts/OMN-9895/dod-guard-pattern/command.yaml && grep -q 'declare -F is_omninode_repo' drift/dod_receipts/OMN-9895/dod-guard-pattern/command.yaml",  # onex-allow-test-fixture OMN-15597 reason="verbatim OCC check_value at the pinned census SHA; the string IS the artifact under test"
}
