# SPDX-FileCopyrightText: 2026 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""L3: assemble metadata + fragments + advanced features into contract YAML.

Replaces the hand-rolled ``dict -> yaml.dump`` serializer. The document is built
as a pydantic model and dumped, so the emitted contract round-trips through a
schema. Fragments are consumed *by type*: the assembler keys each rendered
fragment on its declared :class:`EnumSubcontractType`, never concatenating raw
text. A DO-NOT-EDIT header marks the output as generated.
"""

from __future__ import annotations

from typing import Any

import yaml

from omnimarket.contract_assembly.models import (
    ModelContractAssembleRequest,
    ModelContractDocumentModel,
    ModelContractDraft,
)

_HEADER = (
    "# ONEX v2.0 contract -- generated by the model->contract serialization pipeline\n"
    "# Node: {node_name}\n"
    "# DO NOT EDIT -- regenerate via node_contract_serialize_compute\n"
)


def assemble_contract(request: ModelContractAssembleRequest) -> ModelContractDraft:
    """Assemble a contract document from metadata, fragments, and advanced features.

    Each fragment is placed under its declared type key (consumed by type, not by
    position or free text). The assembled document is validated through
    :class:`ModelContractDocumentModel` before being dumped to YAML.
    """

    subcontracts: dict[str, Any] = {}
    for fragment in request.fragments:
        parsed = yaml.safe_load(fragment.yaml_fragment) or {}
        # Consume by type: pull the entry keyed by the fragment's declared type.
        subcontracts[fragment.type.value] = parsed.get(fragment.type.value, {})

    document = ModelContractDocumentModel(
        metadata=request.metadata.model_dump(mode="json"),
        subcontracts=subcontracts,
        advanced_features=request.advanced_features.model_dump(mode="json"),
    )
    body = yaml.safe_dump(
        document.model_dump(mode="json"),
        default_flow_style=False,
        sort_keys=False,
    )
    header = _HEADER.format(node_name=request.metadata.node_name)
    return ModelContractDraft(contract_yaml=f"{header}\n{body}")


__all__ = ["assemble_contract"]
