# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Door -> forwarder inbound -> ingress seam (OMN-19592, OMN-19593, OMN-19492).

The fixture is the exact envelope the onex-api door
(the cloud repository's ``github_webhook.py::build_wire_envelope``)
publishes for one signed ``pull_request`` delivery, generated by running that
function. It is pinned here because the door lives in another repository and
this seam has never carried a real cloud-to-lab command before
(``tenant_topic_routing.py``: "Leg 1 has never carried a single command").

The test drives the REAL forwarder inbound path
(``ServiceGatewayForwarder.consume_inbound_message``: strict envelope decode,
declared-topic check, both source-tenant tag checks, prefix strip, tenant
stamp) and hands what it publishes locally to the REAL ingress handler. A
change on either side that breaks the other -- a renamed payload key, a
missing tag, an envelope field the strict decode forbids -- fails here.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from uuid import UUID

import pytest
from omnibase_infra.nodes.node_bus_forwarder_effect.models import (
    ModelGatewayCanaryConfig,
    ModelGatewayCloudBusConfig,
    ModelGatewayForwarderConfig,
    ModelGatewayMirrorTopics,
    ModelGatewayTenantIdentity,
)
from omnibase_infra.nodes.node_bus_forwarder_effect.services.service_gateway_forwarder import (
    GatewayRecordRefusedError,
    ServiceGatewayForwarder,
)

from omnimarket.models.model_github_pr_state_observation import (
    ModelGitHubPrStateObservation,
)
from omnimarket.nodes.node_github_webhook_ingress_effect.handlers import (
    HandlerGitHubWebhookIngress,
)
from omnimarket.nodes.node_github_webhook_ingress_effect.models import (
    ModelGitHubPrMergedObservation,
    ModelGitHubWebhookDelivery,
)

pytestmark = [pytest.mark.unit, pytest.mark.asyncio]

FIXTURE = (
    Path(__file__).parents[2] / "fixtures" / "omn19592" / "door_wire_envelope.json"
)
FIXTURE_SECRET = "seam-fixture-secret"
TOPIC = "onex.cmd.github.webhook-delivery.v1"
SLUG = "beta-gateway-canary-79afa7263852"
WIRE_TOPIC = f"tenant-{SLUG}.{TOPIC}"


@dataclass(frozen=True)
class _Message:
    topic: str
    key: bytes | None
    value: bytes
    headers: object | None = None


class _Bus:
    def __init__(self) -> None:
        self.published: list[_Message] = []

    async def publish(
        self,
        topic: str,
        key: bytes | None,
        value: bytes,
        headers: object | None = None,
    ) -> None:
        self.published.append(_Message(topic, key, value, headers))


def _config(tmp_path: Path, principal: str) -> ModelGatewayForwarderConfig:
    return ModelGatewayForwarderConfig(
        tenant_identity=ModelGatewayTenantIdentity(
            tenant_id=UUID("79afa726-3852-464f-b7a4-d4b8b9c75ee7"),
            tenant_slug=SLUG,
            principal_id=principal,
        ),
        cloud_bus=ModelGatewayCloudBusConfig(
            broker_provider_id=UUID("22222222-2222-2222-2222-222222222222"),
            cloud_broker_ref="gateway.cloud.kafka.broker",
            cloud_auth_ref="gateway.cloud.kafka.oauth",
            acl_provisioner_ref="gateway.cloud.kafka.authorization",
            client_id_ref="gateway.cloud.kafka.oauth.client_id",
            client_secret_api_key_ref="infisical://gateway/redpanda-events",
        ),
        local_transport_flavor="containerized",
        dedupe_store_path=tmp_path / "gateway-seam.sqlite3",
        mirror_topics=ModelGatewayMirrorTopics(
            inbound=(TOPIC,),
            outbound=("onex.evt.omnibase-infra.gateway-heartbeat.v1",),
        ),
        canary=ModelGatewayCanaryConfig(
            topic="onex.evt.omnibase-infra.gateway-canary.v1",
            cadence_seconds=30,
            produce_deadline_seconds=8,
            readback_deadline_seconds=12,
        ),
    )


async def test_a_door_envelope_crosses_the_forwarder_and_folds(tmp_path: Path) -> None:
    local, cloud = _Bus(), _Bus()
    service = ServiceGatewayForwarder(
        config=_config(tmp_path, "t-79afa7263852464fb7a4d4b8b9c75ee7"),
        local_bus=local,
        cloud_bus=cloud,
    )
    await service.consume_inbound_message(
        _Message(WIRE_TOPIC, b"k", FIXTURE.read_bytes())
    )

    (published,) = local.published
    assert published.topic == TOPIC
    envelope = json.loads(published.value)
    delivery = ModelGitHubWebhookDelivery.model_validate(envelope["payload"])
    assert delivery.tenant_id == SLUG  # stamped by the forwarder's inbound leg

    out = await HandlerGitHubWebhookIngress(webhook_secret=FIXTURE_SECRET).handle(
        delivery
    )
    state, merged = out.events
    assert isinstance(state, ModelGitHubPrStateObservation)
    assert (state.repo, state.pr_number, state.triage_state) == (
        "OmniNode-ai/omniclaude",
        7,
        "merged",
    )
    assert isinstance(merged, ModelGitHubPrMergedObservation)
    assert merged.ticket == "OMN-1"


async def test_the_forwarder_refuses_a_door_envelope_for_another_principal(
    tmp_path: Path,
) -> None:
    local, cloud = _Bus(), _Bus()
    service = ServiceGatewayForwarder(
        config=_config(tmp_path, "t-00000000000000000000000000000000"),
        local_bus=local,
        cloud_bus=cloud,
    )
    with pytest.raises(GatewayRecordRefusedError, match="principal_id"):
        service.validate_inbound_message(
            _Message(WIRE_TOPIC, b"k", FIXTURE.read_bytes())
        )
    assert local.published == []
