# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Golden-equivalence proof for the finding-aggregator def-B flip (OMN-14654).

RSD mechanical-wave canary via delegation. ``HandlerFindingAggregator.handle()``
moved from ``handle(correlation_id, input_data) -> ModelFindingAggregatorOutput``
(def-A, two positional params) to the canonical
``handle(request) -> ModelFindingAggregatorOutput`` (def-B, single typed-payload
positional; ``correlation_id`` read from ``request.correlation_id``). The handler
body was regenerated by a local model (``onex delegate``, Qwen3.6-35B-A3B); the
business logic is unchanged.

The goldens under
``tests/fixtures/golden/node_finding_aggregator_compute/*.json`` were recorded by
replaying each scenario through the pre-flip def-A ``handle(cid, input)`` body and
capturing byte-canonical output + a sha256 fingerprint. This durable regression
drives the SAME recorded inputs through the live def-B ``handle(request)`` and
asserts byte/fingerprint-identical output — so a future edit to this handler
cannot silently change behavior without failing here (OMN-14589 style, not the
non-canonical adequacy_receipt.py path).

``test_fingerprint_discriminates`` proves the oracle is not a vacuous green: a
one-field perturbation of a recorded output changes the fingerprint.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest
import yaml

from omnimarket.nodes.node_finding_aggregator_compute.handlers.handler_finding_aggregator import (
    HandlerFindingAggregator,
)
from omnimarket.nodes.node_finding_aggregator_compute.models.model_finding_aggregator_input import (
    ModelFindingAggregatorInput,
    ModelSourceFindings,
)
from omnimarket.nodes.node_finding_aggregator_compute.models.model_finding_aggregator_output import (
    ModelFindingAggregatorOutput,
)

pytestmark = pytest.mark.unit

_REPO_ROOT = Path(__file__).resolve().parents[4]
_GOLDEN_DIR = (
    _REPO_ROOT / "tests" / "fixtures" / "golden" / "node_finding_aggregator_compute"
)
_CONTRACT_PATH = (
    _REPO_ROOT
    / "src"
    / "omnimarket"
    / "nodes"
    / "node_finding_aggregator_compute"
    / "contract.yaml"
)
_FAILURE_TERMINAL = "onex.evt.omnimarket.finding-aggregator-failed.v1"

# Recorded from the pre-flip def-A handler; the reviewed scenario pool size.
_EXPECTED_GOLDEN_COUNT = 12


def _fingerprint(output_json: dict[str, Any]) -> str:
    canonical = json.dumps(output_json, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()


def _golden_files() -> list[Path]:
    files = sorted(_GOLDEN_DIR.glob("*.json"))
    assert files, f"no golden fixtures found under {_GOLDEN_DIR}"
    return files


@pytest.mark.parametrize("golden_path", _golden_files(), ids=lambda p: p.stem)
async def test_handle_reproduces_recorded_golden(golden_path: Path) -> None:
    """def-B ``handle(request)`` on the recorded input == the recorded output."""
    golden: dict[str, Any] = json.loads(golden_path.read_text(encoding="utf-8"))
    request = ModelFindingAggregatorInput.model_validate(golden["input"])

    output = await HandlerFindingAggregator().handle(request)

    assert isinstance(output, ModelFindingAggregatorOutput)
    fresh_json = output.model_dump(mode="json")
    # Full-structure equality AND fingerprint equality (byte-identical output).
    assert fresh_json == golden["output"], (
        f"{golden_path.name}: def-B output structure diverged from recorded def-A"
    )
    assert _fingerprint(fresh_json) == golden["output_sha256"], (
        f"{golden_path.name}: def-B output fingerprint diverged from recorded def-A"
    )


def test_golden_fixture_count_matches_expected_pool() -> None:
    """Regression guard: the recorded scenario pool has a known, reviewed size."""
    assert len(_golden_files()) == _EXPECTED_GOLDEN_COUNT


async def test_failure_terminal_declared_and_reachable() -> None:
    """State-coverage (OMN-13781): the declared failure terminal is bound and the
    failure path is genuinely reachable.

    The COMPUTE handler emits no events itself — the runtime synthesizes the
    contract's ``runtime_dispatch.terminal_events.failure`` terminal when
    ``handle()`` raises. Here we (1) bind that declared topic to its literal and
    (2) drive a real internal failure (a non-integer ``line_start`` that raises in
    field extraction) to prove the failure terminal is not dead.
    """
    contract = yaml.safe_load(_CONTRACT_PATH.read_text(encoding="utf-8"))
    declared_failure = contract["runtime_dispatch"]["terminal_events"]["failure"]
    assert declared_failure == "onex.evt.omnimarket.finding-aggregator-failed.v1"

    malformed = ModelFindingAggregatorInput(
        correlation_id=UUID("22222222-2222-4222-8222-222222222222"),
        sources=(
            ModelSourceFindings(
                model_name="model-a",
                findings=(
                    {
                        "rule_id": "R001",
                        "file_path": "src/foo.py",
                        "line_start": "NOT_AN_INT",
                        "severity": "error",
                        "normalized_message": "boom",
                    },
                ),
            ),
        ),
    )
    with pytest.raises(ValueError, match="NOT_AN_INT"):
        await HandlerFindingAggregator().handle(malformed)


def test_fingerprint_discriminates() -> None:
    """The fingerprint oracle is not vacuous: a 1-field perturbation diverges."""
    golden = json.loads(_golden_files()[0].read_text(encoding="utf-8"))
    recorded_fp = golden["output_sha256"]
    assert _fingerprint(golden["output"]) == recorded_fp  # sanity: recompute matches

    perturbed = json.loads(json.dumps(golden["output"]))
    perturbed["total_input_findings"] = int(perturbed["total_input_findings"]) + 1
    assert _fingerprint(perturbed) != recorded_fp, (
        "fingerprint failed to detect a perturbed output — oracle is vacuous"
    )
