# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Generated LLM routing constants.

Generated by scripts/generate_llm_routing_constants.py.
Do not edit by hand; update registry/topology contracts and regenerate.
"""

from __future__ import annotations

from enum import StrEnum, unique

MODEL_REGISTRY_VERSION = "1.0.0"
PRICING_MANIFEST_VERSION = "2026-05-23-initial"
REGISTRY_OBSERVED_AT = "2026-05-23T00:00:00Z"
GENERATED_FROM = ("src/omnimarket/data/model_registry/model_registry_v1.yaml",)


@unique
class EnumLogicalModelKey(StrEnum):
    """Logical model keys declared by the model registry."""

    CLAUDE_OPUS_4_6 = "claude-opus-4-6"
    CLAUDE_SONNET_4_6 = "claude-sonnet-4-6"
    DEEPSEEK_R1_14B = "deepseek-r1-14b"
    DEEPSEEK_R1_32B = "deepseek-r1-32b"
    LLAMA_3_3_70B_FREE = "llama-3.3-70b-free"
    QWEN3_CODER_30B = "qwen3-coder-30b"
    QWEN3_NEXT_80B = "qwen3-next-80b"
    QWEN3_6_35B = "qwen3.6-35b"


@unique
class EnumLlmEndpointRef(StrEnum):
    """Endpoint reference names declared by registry/topology contracts."""

    ANTHROPIC_DELEGATION_URL = "ANTHROPIC_DELEGATION_URL"
    LLM_CODER_FAST_URL = "LLM_CODER_FAST_URL"
    LLM_CODER_URL = "LLM_CODER_URL"
    LLM_DEEPSEEK_R1_URL = "LLM_DEEPSEEK_R1_URL"
    LLM_QWEN3_NEXT_URL = "LLM_QWEN3_NEXT_URL"
    OPENROUTER_URL = "OPENROUTER_URL"


LOGICAL_MODEL_KEYS: tuple[str, ...] = tuple(item.value for item in EnumLogicalModelKey)
LLM_ENDPOINT_REFS: tuple[str, ...] = tuple(item.value for item in EnumLlmEndpointRef)

__all__ = [
    "GENERATED_FROM",
    "LLM_ENDPOINT_REFS",
    "LOGICAL_MODEL_KEYS",
    "MODEL_REGISTRY_VERSION",
    "PRICING_MANIFEST_VERSION",
    "REGISTRY_OBSERVED_AT",
    "EnumLlmEndpointRef",
    "EnumLogicalModelKey",
]
