# SPDX-FileCopyrightText: 2026 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Generate .env.example from the omnimarket Settings model.

Introspects Settings field metadata to produce a commented, categorised
.env.example. Output is deterministic — sorted within each category, no
timestamps, no machine-specific literals. Run from the repo root:

    uv run python scripts/generate_env_example.py

OMN-10581. Wave 1 / Task 9 of the Public-Shippable plan.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure src/ is importable when executed directly.
_repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_repo_root / "src"))

from pydantic.fields import FieldInfo  # noqa: E402

from omnimarket.config.settings import Settings  # noqa: E402

# ---------------------------------------------------------------------------
# Category ordering and membership
# ---------------------------------------------------------------------------

_CATEGORIES: list[tuple[str, str]] = [
    ("service_flags", "Service enable flags"),
    ("kafka", "Kafka / Redpanda"),
    ("postgres", "PostgreSQL"),
    ("qdrant", "Qdrant (vector DB)"),
    ("valkey", "Valkey / Redis-compatible cache"),
    ("llm", "LLM endpoints"),
    ("cloud_api_keys", "Cloud API keys"),
    ("github_linear", "GitHub / Linear"),
    ("memory", "Memory service / embedding"),
    ("onex_runtime", "ONEX runtime / emit daemon / infra targets"),
    ("misc", "Miscellaneous"),
]

_FIELD_CATEGORY: dict[str, str] = {
    # service flags
    "enable_kafka": "service_flags",
    "enable_postgres": "service_flags",
    "enable_qdrant": "service_flags",
    "enable_valkey": "service_flags",
    "enable_memory_service": "service_flags",
    # kafka
    "kafka_bootstrap_servers": "kafka",
    "kafka_broker": "kafka",
    "kafka_consumer_group": "kafka",
    "kafka_environment": "kafka",
    "redpanda_admin_host": "kafka",
    "redpanda_admin_port": "kafka",
    # postgres
    "postgres_host": "postgres",
    "postgres_port": "postgres",
    "postgres_database": "postgres",
    "postgres_user": "postgres",
    "postgres_password": "postgres",
    "omnibase_infra_db_url": "postgres",
    "omnidash_analytics_db_url": "postgres",
    # qdrant
    "qdrant_host": "qdrant",
    "qdrant_port": "qdrant",
    # valkey
    "valkey_host": "valkey",
    "valkey_port": "valkey",
    # llm
    "llm_coder_url": "llm",
    "llm_coder_model_id": "llm",
    "llm_coder_fast_url": "llm",
    "llm_coder_fast_model_id": "llm",
    "llm_reasoner_url": "llm",
    "llm_reasoner_model_id": "llm",
    "llm_embedding_url": "llm",
    "llm_embedding_model_id": "llm",
    "llm_glm_url": "llm",
    "llm_glm_api_key": "llm",
    "llm_glm_model_name": "llm",
    # cloud api keys
    "openai_api_key": "cloud_api_keys",
    "google_api_key": "cloud_api_keys",
    "gemini_api_key": "cloud_api_keys",
    "anthropic_api_key": "cloud_api_keys",
    # github / linear
    "github_token": "github_linear",
    "gh_pat": "github_linear",
    "linear_api_key": "github_linear",
    # memory
    "embedding_model_url": "memory",
    # onex runtime
    "onex_emit_socket_path": "onex_runtime",
    "onex_emit_spool_dir": "onex_runtime",
    "onex_emit_daemon_socket": "onex_runtime",
    "onex_state_root": "onex_runtime",
    "onex_dashboard_api": "onex_runtime",
    "onex_infra_ssh_target": "onex_runtime",
    "onex_target_runtime_address": "onex_runtime",
}


def _env_name(field_name: str) -> str:
    return field_name.upper()


def _default_repr(field_info: FieldInfo) -> str:
    default = field_info.default
    if default is None:
        return ""
    # SecretStr default: extract inner value
    try:
        from pydantic import SecretStr

        if isinstance(default, SecretStr):
            return default.get_secret_value()
    except ImportError:
        pass
    if isinstance(default, bool):
        return "true" if default else "false"
    if isinstance(default, int):
        return str(default) if default != 0 else ""
    if isinstance(default, str):
        return default
    return ""


def generate(output_path: Path | None = None) -> str:
    """Generate .env.example content and optionally write to disk."""
    model_fields: dict[str, FieldInfo] = Settings.model_fields

    # bucket fields into categories
    buckets: dict[str, list[str]] = {cat_id: [] for cat_id, _ in _CATEGORIES}

    for field_name in model_fields:
        cat = _FIELD_CATEGORY.get(field_name, "misc")
        buckets.setdefault(cat, [])
        buckets[cat].append(field_name)

    # sort within each category for determinism
    for cat_id in buckets:
        buckets[cat_id].sort()

    lines: list[str] = [
        "# .env.example — omnimarket",
        "#",
        "# Generated by scripts/generate_env_example.py from the Settings model.",
        "# Do NOT hand-edit. Re-generate after adding or removing Settings fields:",
        "#",
        "#   uv run python scripts/generate_env_example.py",
        "#",
        "# All values are empty / false / 0 by default.",
        "# Enable a service by setting its ENABLE_* flag to true and filling",
        "# in the required fields documented below.",
        "",
    ]

    for cat_id, cat_label in _CATEGORIES:
        fields_in_cat = buckets.get(cat_id, [])
        if not fields_in_cat:
            continue

        lines.append(f"# {'=' * 70}")
        lines.append(f"# {cat_label}")
        lines.append(f"# {'=' * 70}")
        lines.append("")

        for field_name in fields_in_cat:
            field_info = model_fields[field_name]
            description = field_info.description or ""
            env_key = _env_name(field_name)
            default_val = _default_repr(field_info)

            # wrap description at ~78 chars
            desc_words = description.split()
            desc_lines: list[str] = []
            current = ""
            for word in desc_words:
                probe = f"{current} {word}".strip()
                if len(probe) > 76:
                    if current:
                        desc_lines.append(current)
                    current = word
                else:
                    current = probe
            if current:
                desc_lines.append(current)

            for dl in desc_lines:
                lines.append(f"# {dl}")
            lines.append(f"# {env_key}={default_val}")
            lines.append("")

    # Strip trailing blank lines so the file ends with exactly one newline.
    while lines and lines[-1] == "":
        lines.pop()
    content = "\n".join(lines) + "\n"

    if output_path is not None:
        output_path.write_text(content, encoding="utf-8")
        print(f"Written: {output_path}")

    return content


if __name__ == "__main__":
    repo_root = Path(__file__).resolve().parent.parent
    generate(output_path=repo_root / ".env.example")
